<?php

/**
 * @file
 * Contains event_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_log module.
    case 'help.page.event_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event Log module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function event_log_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if(\Drupal::service('event_log.logger')->checkIfEntityIsEnabled($entity)){
    \Drupal::service('event_log.logger')->createLogEntity($entity,'insert');
  }
}

/**
 * Implements hook_entity_update().
 */
function event_log_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  if(\Drupal::service('event_log.logger')->checkIfEntityIsEnabled($entity)){
    \Drupal::service('event_log.logger')->createLogEntity($entity,'update');
  }
}

/**
 * Implements hook_entity_delete().
 */
function event_log_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if(\Drupal::service('event_log.logger')->checkIfEntityIsEnabled($entity)){
    \Drupal::service('event_log.logger')->createLogEntity($entity,'delete');
  }
}

/**
 * Implements hook_cron().
 */
function event_log_cron() {
  \Drupal::service('event_log.logger')->PurgeOldLogs();
}